### ISSUE TITLE
Generate character-based L-system expansion

### ISSUE THREAD

**Issue by TIF141** [TIF141/l-systems#1]
Deterministic, context-free character-based L-system expansion in the console.

**Comment by TIF141** [comment]
[] example task

**Comment by TIF141** [comment]
```[tasklist]
### My tasks
- [ ] https://github.com/octo-org/octo-repo/issues/45
- [ ] Draft task
```

**Comment by TIF141** [comment]
- [ ] example

**Comment by malonej501** [comment]
- [ ] Create default L-system class
- [ ] Add methods for specifying alphabet, rules and initial state
